[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' https://pagead2.googlesyndication.com https://fundingchoicesmessages.google.com 'unsafe-inline' 'unsafe-eval';"
